### ISSUE TITLE
[I ran into an issue] Teams bot application and aadApp/create in m365agents.local.yml

### ISSUE THREAD

**Issue by TPIvan** [MicrosoftDocs/msteams-docs#12999]
### Type of issue

Outdated article

### Feedback

I have created a project by wheather forcast template in 365 agents toolkit in Visual studio.  
I am editing `m365agents.local.yml`
The instructions says _Add aadApp/create under provision_ but there is a such section already. 
```
  # Create or reuse an existing Microsoft Entra application for bot.
  - uses: aadApp/create
    with:
      # The Microsoft Entra application's display name
      name: MyM365Agent3${{APP_NAME_SUFFIX}}
      generateClientSecret: true
      signInAudience: AzureADMultipleOrgs
    writeToEnvironmentFile:
      # The Microsoft Entra application's client id created for bot.
      clientId: BOT_ID
      # The Microsoft Entra application's client secret created for bot.
      clientSecret: SECRET_BOT_PASSWORD
      # The Microsoft Entra application's object id created for bot.
      objectId: BOT_OBJECT_ID
```
Should be realy a new section added or the existing one should be updated?

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/add-single-sign-on-vs#teams-bot-application

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/toolkit-v4/add-single-sign-on-vs.md

### Author

@surbhigupta

### Document Id

f5590168-8c16-04cb-4c56-a7d76ea7d935

### Platform Id

42e04429-d075-6f28-28fa-ae0f0380ff5f
