### ISSUE TITLE
[I ran into an issue] Teams bot application unclear instructions for file/createOrUpdateJsonFile in m365agents.local.yml.

### ISSUE THREAD

**Issue by TPIvan** [MicrosoftDocs/msteams-docs#13000]
### Type of issue

Outdated article

### Feedback

I have created a project by wheather forcast template in 365 agents toolkit in Visual studio.  
I am editing `m365agents.local.yml`
The instructions says _Update file/createOrUpdateJsonFile under provision_ but the section is already present and it is not clear how it shoud be modified.  Should I just add  `TeamsFx:` section or should I remove existing ones? Also the path to the file seems to be wrong. Or is it the same path written other way?
```
- uses: file/createOrUpdateJsonFile
        with:
          target: ./appsettings.Development.json
          appsettings:
            BOT_ID: ${{BOT_ID}}
            BOT_PASSWORD: ${{SECRET_BOT_PASSWORD}}
            TeamsFx:
              Authentication:
                ClientId: ${{AAD_APP_CLIENT_ID}}
                ClientSecret: ${{SECRET_AAD_APP_CLIENT_SECRET}}
                OAuthAuthority: ${{AAD_APP_OAUTH_AUTHORITY}}/${{AAD_APP_TENANT_ID}}
                ApplicationIdUri: api://botid-${{BOT_ID}}
                Bot:
                  InitiateLoginEndpoint: https://${{BOT_DOMAIN}}/bot-auth-start
```
and actual section in the file is 
 ```
- uses: file/createOrUpdateJsonFile
    with:
      target: ../ProjecName/appsettings.Development.json
      content:
        TokenValidation:
          Audiences:
            ClientId: ${{BOT_ID}}
        Connections:
          BotServiceConnection:
            Settings:
              AuthType: "ClientSecret"
              AuthorityEndpoint: "https://login.microsoftonline.com/botframework.com"
              ClientId: ${{BOT_ID}}
              ClientSecret: ${{SECRET_BOT_PASSWORD}}
        Azure:
          OpenAIApiKey: ${{SECRET_AZURE_OPENAI_API_KEY}}
          OpenAIEndpoint: ${{AZURE_OPENAI_ENDPOINT}}
          OpenAIDeploymentName: ${{AZURE_OPENAI_DEPLOYMENT_NAME}}

```

### Page URL

https://learn.microsoft.com/en-us/microsoftteams/platform/toolkit/toolkit-v4/add-single-sign-on-vs#teams-bot-application

### Content source URL

https://github.com/MicrosoftDocs/msteams-docs/blob/main/msteams-platform/toolkit/toolkit-v4/add-single-sign-on-vs.md

### Author

@surbhigupta

### Document Id

f5590168-8c16-04cb-4c56-a7d76ea7d935

### Platform Id

42e04429-d075-6f28-28fa-ae0f0380ff5f
